// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sql

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Request struct {
	ID                        int32
	Url                       string
	Headers                   json.RawMessage
	Ctx                       pqtype.NullRawMessage
	Depth                     int32
	Method                    string
	Body                      []byte
	Responsecharacterencoding sql.NullString
	Proxyurl                  sql.NullString
}
