// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: request.sql

package sql

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO request (URL, Headers, Ctx, Depth, Method, Body, ResponseCharacterEncoding, ProxyURL)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING ID
`

type CreateRequestParams struct {
	Url                       string
	Headers                   json.RawMessage
	Ctx                       pqtype.NullRawMessage
	Depth                     int32
	Method                    string
	Body                      []byte
	Responsecharacterencoding sql.NullString
	Proxyurl                  sql.NullString
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.Url,
		arg.Headers,
		arg.Ctx,
		arg.Depth,
		arg.Method,
		arg.Body,
		arg.Responsecharacterencoding,
		arg.Proxyurl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
